replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "cibexon/kbot"
  pullPolicy: IfNotPresent
  tag: "v1.0.5-0c55eb7"
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
service:
  port: 80
# Секції для лінтера
autoscaling:
  enabled: false
serviceAccount:
  create: true
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
