name: KBOT-CICD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  TARGETARCH: amd64
  TARGETOS: linux
  CGO_ENABLED: 0

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: make build TARGETARCH=${{ env.TARGETARCH }} TARGETOS=${{ env.TARGETOS }}

  cd:
    name: CD
    needs: ci
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write # Дозволяє пушити в GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: GitHub Container Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          APP: "kbot"
          OWNER: ${{ github.repository_owner }}
        run: |
          LOW_OWNER=$(echo "${OWNER}" | tr '[:upper:]' '[:lower:]')
          make image push \
            TARGETARCH=${{ env.TARGETARCH }} \
            TARGETOS=${{ env.TARGETOS }} \
            VERSION=${{ env.VERSION }} \
            OWNER=${LOW_OWNER}

      - name: Update Helm chart
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/values.yaml
          git commit -m "chore: update version to ${{ env.VERSION }}"
          git push

      - name: Cleanup
        run: make clean TARGETARCH=${{ env.TARGETARCH }}
